
'use client';

import { useState, useEffect } from 'react';
import { Temple, ContentType } from '@/lib/types';
import { Plus, Edit2, Trash2, X, Save, Upload, Loader2, Check, Calendar } from 'lucide-react';

const contentOptions: { label: string; key: ContentType }[] = [
    { label: 'Morning Aarti', key: 'morningAarti' },
    { label: 'Evening Aarti', key: 'eveningAarti' },
    { label: 'Morning Darshan', key: 'morningDarshan' },
    { label: 'Evening Darshan', key: 'eveningDarshan' },
];

const getTodayString = () => new Date().toLocaleDateString('en-CA');

export default function TemplesPage() {
    const [temples, setTemples] = useState<Temple[]>([]);
    const [loading, setLoading] = useState(true);
    const [isEditing, setIsEditing] = useState(false);
    const [currentTemple, setCurrentTemple] = useState<Partial<Temple>>({});
    const [uploadingState, setUploadingState] = useState<Record<string, boolean>>({});
    const [selectedDate, setSelectedDate] = useState<string>(getTodayString());

    // Fetch Temples on Mount
    useEffect(() => {
        fetchTemples();
    }, []);

    const fetchTemples = async () => {
        try {
            const res = await fetch('/api/temples');
            const data = await res.json();
            setTemples(data);
            setLoading(false);
        } catch (error) {
            console.error('Failed to fetch temples', error);
            setLoading(false);
        }
    };

    const handleDelete = async (id: string) => {
        if (confirm('Are you sure you want to delete this temple?')) {
            try {
                const res = await fetch(`/api/temples?id=${id}`, { method: 'DELETE' });
                if (res.ok) {
                    fetchTemples();
                } else {
                    alert('Failed to delete');
                }
            } catch (error) {
                console.error(error);
                alert('Error deleting temple');
            }
        }
    };

    const handleEdit = (temple: Temple) => {
        const safeTemple = {
            ...temple,
            activeContentTypes: temple.activeContentTypes || ['morningAarti', 'eveningAarti', 'morningDarshan', 'eveningDarshan'],
            videos: temple.videos || {}
        };
        setCurrentTemple(JSON.parse(JSON.stringify(safeTemple)));
        setIsEditing(true);
        setSelectedDate(getTodayString());
    };

    const handleCreate = () => {
        setCurrentTemple({
            // ID will be generated by Server if not provided, but we can send one if we want.
            // Let server handle ID generation for safety.
            activeContentTypes: ['morningAarti', 'eveningAarti', 'morningDarshan', 'eveningDarshan'],
            videos: {}
        });
        setIsEditing(true);
        setSelectedDate(getTodayString());
    };

    const handleSave = async () => {
        if (!currentTemple.name || !currentTemple.nameHindi || !currentTemple.location || !currentTemple.locationHindi || !currentTemple.description || !currentTemple.descriptionHindi)
            return alert('All fields (English & Hindi) required');

        try {
            const isNew = !currentTemple.id;
            const url = '/api/temples';
            const method = isNew ? 'POST' : 'PUT';

            const res = await fetch(url, {
                method,
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(currentTemple)
            });

            if (res.ok) {
                fetchTemples();
                setIsEditing(false);
            } else {
                const err = await res.json();
                alert('Save failed: ' + (err.error || 'Unknown error'));
            }
        } catch (error) {
            console.error(error);
            alert('Error saving temple');
        }
    };

    const toggleContentType = (type: ContentType) => {
        const currentTypes = currentTemple.activeContentTypes || [];
        if (currentTypes.includes(type)) {
            setCurrentTemple({
                ...currentTemple,
                activeContentTypes: currentTypes.filter(t => t !== type)
            });
        } else {
            setCurrentTemple({
                ...currentTemple,
                activeContentTypes: [...currentTypes, type]
            });
        }
    };

    const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>, targetField: 'image' | ContentType) => {
        const file = e.target.files?.[0];
        if (!file) return;

        setUploadingState(prev => ({ ...prev, [targetField]: true }));

        try {
            const formData = new FormData();
            formData.append('file', file);

            const res = await fetch('/api/upload', {
                method: 'POST',
                body: formData,
            });
            const data = await res.json();

            if (data.success) {
                if (targetField === 'image') {
                    setCurrentTemple(prev => ({ ...prev, image: data.url }));
                } else {
                    // Video/Image Upload for Specific DATE
                    const existingVideosForDate = currentTemple.videos?.[selectedDate] || {};

                    setCurrentTemple(prev => ({
                        ...prev,
                        videos: {
                            ...prev.videos,
                            [selectedDate]: {
                                ...existingVideosForDate,
                                [targetField]: data.url
                            }
                        }
                    }));
                }
            } else {
                alert('Upload failed');
            }
        } catch (err) {
            console.error(err);
            alert('Error uploading file');
        } finally {
            setUploadingState(prev => ({ ...prev, [targetField]: false }));
        }
    };

    if (loading) return <div className="p-8"><Loader2 className="animate-spin text-saffron" size={40} /></div>;

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <h1 className="text-2xl font-bold text-saffron-dark">Temple Management</h1>
                <button
                    onClick={handleCreate}
                    className="bg-saffron hover:bg-saffron-dark text-white px-4 py-2 rounded-lg flex items-center gap-2 shadow-sm transition-colors"
                >
                    <Plus size={18} /> Add Temple
                </button>
            </div>

            {isEditing ? (
                <div className="bg-white p-8 rounded-xl border border-saffron/20 shadow-md animate-in fade-in zoom-in-95 duration-200">
                    <div className="flex justify-between items-center mb-6">
                        <h2 className="text-xl font-bold text-brown">
                            {currentTemple.id ? 'Edit Temple' : 'New Temple'}
                        </h2>
                        <button onClick={() => setIsEditing(false)} className="text-gray-400 hover:text-red-500">
                            <X size={24} />
                        </button>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                        <div className="space-y-6">
                            <div className="space-y-4">
                                <h3 className="font-semibold text-brown-dark border-b pb-2">1. Temple Details</h3>
                                <div>
                                    <label className="block text-sm font-medium text-brown mb-1">Temple Name (English)</label>
                                    <input
                                        className="w-full p-2 border rounded-md focus:border-saffron focus:ring-1 focus:ring-saffron outline-none"
                                        value={currentTemple.name || ''}
                                        onChange={e => setCurrentTemple({ ...currentTemple, name: e.target.value })}
                                        placeholder="E.g. Somnath Temple"
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-brown mb-1">Temple Name (Hindi)</label>
                                    <input
                                        className="w-full p-2 border rounded-md focus:border-saffron focus:ring-1 focus:ring-saffron outline-none"
                                        value={currentTemple.nameHindi || ''}
                                        onChange={e => setCurrentTemple({ ...currentTemple, nameHindi: e.target.value })}
                                        placeholder="E.g. सोमनाथ मंदिर"
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-brown mb-1">Location (English)</label>
                                    <input
                                        className="w-full p-2 border rounded-md focus:border-saffron focus:ring-1 focus:ring-saffron outline-none"
                                        value={currentTemple.location || ''}
                                        onChange={e => setCurrentTemple({ ...currentTemple, location: e.target.value })}
                                        placeholder="E.g. Gujarat"
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-brown mb-1">Location (Hindi)</label>
                                    <input
                                        className="w-full p-2 border rounded-md focus:border-saffron focus:ring-1 focus:ring-saffron outline-none"
                                        value={currentTemple.locationHindi || ''}
                                        onChange={e => setCurrentTemple({ ...currentTemple, locationHindi: e.target.value })}
                                        placeholder="E.g. गुजरात"
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-brown mb-1">Temple Image</label>
                                    <div className="flex items-center gap-3">
                                        {currentTemple.image && (
                                            <img src={currentTemple.image} alt="Preview" className="w-16 h-16 rounded object-cover border" />
                                        )}
                                        <label className="flex-1 cursor-pointer">
                                            <div className={`border-2 border-dashed rounded-lg p-3 flex items-center justify-center gap-2 transition-colors ${uploadingState['image'] ? 'bg-gray-50 border-gray-300' : 'border-saffron/40 hover:bg-saffron/5'}`}>
                                                {uploadingState['image'] ? (
                                                    <Loader2 className="animate-spin text-saffron" size={20} />
                                                ) : (
                                                    <>
                                                        <Upload size={18} className="text-saffron" />
                                                        <span className="text-sm text-gray-600">Upload Image</span>
                                                    </>
                                                )}
                                            </div>
                                            <input type="file" accept="image/*" className="hidden" onChange={(e) => handleFileUpload(e, 'image')} />
                                        </label>
                                    </div>
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-brown mb-1">Description (English)</label>
                                    <textarea
                                        className="w-full p-2 border rounded-md focus:border-saffron focus:ring-1 focus:ring-saffron outline-none"
                                        rows={3}
                                        value={currentTemple.description || ''}
                                        onChange={e => setCurrentTemple({ ...currentTemple, description: e.target.value })}
                                        placeholder="Enter details..."
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-brown mb-1">Description (Hindi)</label>
                                    <textarea
                                        className="w-full p-2 border rounded-md focus:border-saffron focus:ring-1 focus:ring-saffron outline-none"
                                        rows={3}
                                        value={currentTemple.descriptionHindi || ''}
                                        onChange={e => setCurrentTemple({ ...currentTemple, descriptionHindi: e.target.value })}
                                        placeholder="विवरण दर्ज करें..."
                                    />
                                </div>
                            </div>

                            <div className="space-y-3 p-4 bg-cream rounded-lg border border-saffron/20">
                                <h3 className="font-semibold text-brown-dark text-sm">2. Enable Content Types</h3>
                                <div className="grid grid-cols-2 gap-2">
                                    {contentOptions.map((opt) => (
                                        <label key={opt.key} className="flex items-center gap-2 cursor-pointer">
                                            <div className={`w-5 h-5 rounded border flex items-center justify-center transition-colors ${currentTemple.activeContentTypes?.includes(opt.key) ? 'bg-saffron border-saffron' : 'bg-white border-gray-300'}`}>
                                                {currentTemple.activeContentTypes?.includes(opt.key) && <Check size={14} className="text-white" />}
                                            </div>
                                            <input
                                                type="checkbox"
                                                className="hidden"
                                                checked={currentTemple.activeContentTypes?.includes(opt.key) || false}
                                                onChange={() => toggleContentType(opt.key)}
                                            />
                                            <span className="text-sm font-medium text-brown">{opt.label}</span>
                                        </label>
                                    ))}
                                </div>
                            </div>
                        </div>

                        <div className="space-y-4">
                            <div className="flex items-center justify-between border-b pb-2">
                                <h3 className="font-semibold text-brown-dark">3. Content Upload</h3>
                            </div>

                            <div className="bg-gray-50 p-3 rounded-lg border flex items-center gap-3">
                                <Calendar className="text-brown" size={20} />
                                <div className="flex-1">
                                    <label className="block text-xs font-bold text-gray-500 uppercase">Select Date</label>
                                    <input
                                        type="date"
                                        className="w-full bg-transparent font-medium text-brown-dark outline-none mt-1"
                                        value={selectedDate}
                                        onChange={(e) => setSelectedDate(e.target.value)}
                                    />
                                </div>
                                <div className="text-xs text-saffron-dark font-medium px-2 py-1 bg-saffron/10 rounded">
                                    {selectedDate === getTodayString() ? 'Today' : ''}
                                </div>
                            </div>

                            <div className="space-y-4">
                                {contentOptions.map((opt) => {
                                    const isEnabled = currentTemple.activeContentTypes?.includes(opt.key);
                                    if (!isEnabled) return null;

                                    const existingContent = currentTemple.videos?.[selectedDate]?.[opt.key];
                                    const isUploading = uploadingState[opt.key];
                                    const isAarti = opt.key.toLowerCase().includes('aarti');
                                    const acceptType = isAarti ? 'video/*' : 'image/*';

                                    return (
                                        <div key={opt.key} className="p-3 border rounded-lg hover:border-saffron/30 transition-colors bg-white">
                                            <div className="flex justify-between items-center mb-2">
                                                <label className="text-xs font-bold text-brown uppercase tracking-wider">
                                                    {opt.label} <span className="text-gray-400 font-normal">({isAarti ? 'Video' : 'Photo'})</span>
                                                </label>
                                                {existingContent && (
                                                    <span className="text-xs text-green-600 font-medium overflow-hidden max-w-[100px] truncate text-right">Uploaded ✓</span>
                                                )}
                                            </div>

                                            <div className="flex gap-2">
                                                <label className="flex-1 cursor-pointer">
                                                    <div className={`border border-dashed rounded-md p-2 flex items-center justify-center gap-2 bg-white transition-all ${isUploading ? 'bg-gray-100' : 'hover:border-saffron'}`}>
                                                        {isUploading ? (
                                                            <Loader2 className="animate-spin text-saffron" size={20} />
                                                        ) : (
                                                            <>
                                                                <Upload size={16} className="text-gray-400" />
                                                                <span className="text-sm text-gray-500 truncate">
                                                                    {existingContent ? existingContent.split('/').pop() : `Click to Upload ${isAarti ? 'Video' : 'Photo'}`}
                                                                </span>
                                                            </>
                                                        )}
                                                    </div>
                                                    <input
                                                        type="file"
                                                        accept={acceptType}
                                                        className="hidden"
                                                        disabled={isUploading}
                                                        onChange={(e) => handleFileUpload(e, opt.key)}
                                                    />
                                                </label>
                                                {existingContent && (
                                                    <button
                                                        onClick={() => {
                                                            const vids = currentTemple.videos?.[selectedDate] || {};
                                                            delete vids[opt.key];
                                                            setCurrentTemple({ ...currentTemple, videos: { ...currentTemple.videos, [selectedDate]: vids } });
                                                        }}
                                                        className="p-2 text-red-500 hover:bg-red-50 rounded"
                                                    >
                                                        <X size={16} />
                                                    </button>
                                                )}
                                            </div>
                                            {!isAarti && existingContent && (
                                                <div className="mt-2">
                                                    <img src={existingContent} alt="Preview" className="w-full h-32 object-contain rounded bg-black/5" />
                                                </div>
                                            )}
                                        </div>
                                    );
                                })}
                            </div>
                        </div>
                    </div>

                    <div className="mt-8 flex justify-end gap-3 border-t pt-4">
                        <button onClick={() => setIsEditing(false)} className="px-4 py-2 text-gray-600 hover:bg-gray-100 rounded-lg">Cancel</button>
                        <button onClick={handleSave} className="px-6 py-2 bg-saffron hover:bg-saffron-dark text-white font-medium rounded-lg flex items-center gap-2 shadow-sm">
                            <Save size={18} /> Save Temple
                        </button>
                    </div>
                </div>
            ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {temples.map((temple) => (
                        <div key={temple.id} className="bg-white rounded-xl shadow-sm border border-saffron/20 overflow-hidden hover:shadow-md transition-shadow">
                            <div className="h-48 bg-gray-200 relative">
                                {temple.image ? (
                                    <img src={temple.image} alt={temple.name} className="w-full h-full object-cover" />
                                ) : (
                                    <div className="w-full h-full flex items-center justify-center text-gray-400">
                                        <div className="text-4xl">🕉️</div>
                                    </div>
                                )}
                                <div className="absolute top-2 right-2 flex gap-2">
                                    <button onClick={() => handleEdit(temple)} className="p-2 bg-white/90 rounded-full text-blue-600"><Edit2 size={16} /></button>
                                    <button onClick={() => handleDelete(temple.id)} className="p-2 bg-white/90 rounded-full text-red-600"><Trash2 size={16} /></button>
                                </div>
                            </div>
                            <div className="p-4">
                                <h3 className="font-bold text-lg text-brown-dark truncate">{temple.name}</h3>
                                <p className="text-sm text-gray-500 mt-1">{temple.location}</p>
                                <div className="flex gap-2 mt-3">
                                    <span className="text-xs bg-saffron/10 text-saffron-dark px-2 py-1 rounded border border-saffron/20">
                                        Dates with Content: {Object.keys(temple.videos || {}).length}
                                    </span>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
}
